# Use a Node.js base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the backend code to the container
COPY . /app

# Install dependencies
RUN npm install

# Expose the port your Node.js app is listening on
EXPOSE 3000

# Start the Node.js application
CMD ["node", "backend.js"]
