version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sagar
      MYSQL_DATABASE: WEB_D_project
    ports:
      - "3307:3306"
